/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clasesproyecto.listas.ProCable;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author XavierKrostya
 */
public class OpcionPersonal extends javax.swing.JFrame {

    private ProCable procable;
    /**
     * Creates new form OpcionPersonal
     */
    public OpcionPersonal(ProCable procable) {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        this.procable = procable;
        /*Para poder cargar la imagen del icono*/
        setIconImage(new ImageIcon(getClass().getResource("/Imágenes/network.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbSalir = new javax.swing.JButton();
        lblWorld1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        BtnAgregarPersonal = new javax.swing.JButton();
        BtnEliminarPersonal = new javax.swing.JButton();
        BtnModificarPersonal = new javax.swing.JButton();
        BtnMostrarPersonal = new javax.swing.JButton();
        BtnVolverAlMenu = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbSalir.setBackground(new java.awt.Color(102, 0, 102));
        jbSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbSalir.setForeground(new java.awt.Color(255, 255, 255));
        jbSalir.setText("Salir");
        jbSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 70, 50));

        lblWorld1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/user.png"))); // NOI18N
        getContentPane().add(lblWorld1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 140, 160));

        lblTitulo.setFont(new java.awt.Font("Cordia New", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Menú Personal");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 220, -1));

        BtnAgregarPersonal.setBackground(new java.awt.Color(102, 0, 102));
        BtnAgregarPersonal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BtnAgregarPersonal.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregarPersonal.setText("Agregar");
        BtnAgregarPersonal.setBorder(null);
        BtnAgregarPersonal.setContentAreaFilled(false);
        BtnAgregarPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAgregarPersonal.setOpaque(true);
        BtnAgregarPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarPersonalActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAgregarPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 200, 40));

        BtnEliminarPersonal.setBackground(new java.awt.Color(102, 0, 102));
        BtnEliminarPersonal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BtnEliminarPersonal.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminarPersonal.setText("Eliminar");
        BtnEliminarPersonal.setBorder(null);
        BtnEliminarPersonal.setContentAreaFilled(false);
        BtnEliminarPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEliminarPersonal.setOpaque(true);
        BtnEliminarPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarPersonalActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEliminarPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 200, 40));

        BtnModificarPersonal.setBackground(new java.awt.Color(102, 0, 102));
        BtnModificarPersonal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BtnModificarPersonal.setForeground(new java.awt.Color(255, 255, 255));
        BtnModificarPersonal.setText("Modificar");
        BtnModificarPersonal.setBorder(null);
        BtnModificarPersonal.setContentAreaFilled(false);
        BtnModificarPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnModificarPersonal.setOpaque(true);
        BtnModificarPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarPersonalActionPerformed(evt);
            }
        });
        getContentPane().add(BtnModificarPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 200, 40));

        BtnMostrarPersonal.setBackground(new java.awt.Color(102, 0, 102));
        BtnMostrarPersonal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BtnMostrarPersonal.setForeground(new java.awt.Color(255, 255, 255));
        BtnMostrarPersonal.setText("Mostrar");
        BtnMostrarPersonal.setBorder(null);
        BtnMostrarPersonal.setContentAreaFilled(false);
        BtnMostrarPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnMostrarPersonal.setOpaque(true);
        BtnMostrarPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMostrarPersonalActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMostrarPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 200, 40));

        BtnVolverAlMenu.setBackground(new java.awt.Color(102, 0, 102));
        BtnVolverAlMenu.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BtnVolverAlMenu.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolverAlMenu.setText("Volver al Inicio");
        BtnVolverAlMenu.setBorder(null);
        BtnVolverAlMenu.setContentAreaFilled(false);
        BtnVolverAlMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnVolverAlMenu.setOpaque(true);
        BtnVolverAlMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverAlMenuActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVolverAlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 200, 40));

        lblFondo.setForeground(new java.awt.Color(102, 102, 102));
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/fondoMoradoP.jpg"))); // NOI18N
        lblFondo.setPreferredSize(new java.awt.Dimension(760, 590));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbSalirActionPerformed

    private void BtnAgregarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarPersonalActionPerformed
        SubVentanaFormularioPersonal form = new SubVentanaFormularioPersonal(procable);
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnAgregarPersonalActionPerformed

    private void BtnEliminarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarPersonalActionPerformed
        
        if((this.procable).personal.estaVacio()){
            JOptionPane.showMessageDialog(null, "No hay empleados por eliminar!");
        }
        else{
            VentanaRutEliminarPersonal formrut = new VentanaRutEliminarPersonal(procable);
            formrut.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_BtnEliminarPersonalActionPerformed

    private void BtnMostrarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMostrarPersonalActionPerformed
        if((this.procable).personal.estaVacio()){
            JOptionPane.showMessageDialog(null, "No hay empleados por mostrar!");
        }
        else{
            VentanaRutMostrarPersonal formrut = new VentanaRutMostrarPersonal(procable);
            formrut.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_BtnMostrarPersonalActionPerformed

    private void BtnVolverAlMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverAlMenuActionPerformed
        MenuPrincipal principal = new MenuPrincipal(procable);
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnVolverAlMenuActionPerformed

    private void BtnModificarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarPersonalActionPerformed
        if((this.procable).personal.estaVacio()){
            JOptionPane.showMessageDialog(null, "No hay empleados por modificar!");
        }
        else{
            VentanaRutModificarPersonal submenu = new VentanaRutModificarPersonal(procable);
            submenu.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_BtnModificarPersonalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarPersonal;
    private javax.swing.JButton BtnEliminarPersonal;
    private javax.swing.JButton BtnModificarPersonal;
    private javax.swing.JButton BtnMostrarPersonal;
    private javax.swing.JButton BtnVolverAlMenu;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblWorld1;
    // End of variables declaration//GEN-END:variables
}
