/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clasesproyecto.listas.ProCable;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author XavierKrostya
 */
public class OpcionPlan extends javax.swing.JFrame {
    
    private ProCable procable;
    /**
     * Creates new form OpcionPlan
     */
    public OpcionPlan(ProCable procable) {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        this.procable = procable;
        /*Para poder cargar la imagen del icono*/
        setIconImage(new ImageIcon(getClass().getResource("/Imágenes/network.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWorld1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        BtnAgregar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnVerMas = new javax.swing.JButton();
        BtnVolverAlMenu = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWorld1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/network_connection_control_panel.png"))); // NOI18N
        getContentPane().add(lblWorld1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 130, 130));

        lblTitulo.setFont(new java.awt.Font("Cordia New", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Menú Planes");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 190, -1));

        BtnAgregar.setBackground(new java.awt.Color(102, 0, 102));
        BtnAgregar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregar.setText("Agregar");
        BtnAgregar.setBorder(null);
        BtnAgregar.setContentAreaFilled(false);
        BtnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAgregar.setOpaque(true);
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 210, 40));

        BtnEliminar.setBackground(new java.awt.Color(102, 0, 102));
        BtnEliminar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminar.setText("Eliminar");
        BtnEliminar.setBorder(null);
        BtnEliminar.setContentAreaFilled(false);
        BtnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEliminar.setOpaque(true);
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 210, 40));

        BtnVerMas.setBackground(new java.awt.Color(102, 0, 102));
        BtnVerMas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BtnVerMas.setForeground(new java.awt.Color(255, 255, 255));
        BtnVerMas.setText("Ver más");
        BtnVerMas.setBorder(null);
        BtnVerMas.setContentAreaFilled(false);
        BtnVerMas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnVerMas.setOpaque(true);
        getContentPane().add(BtnVerMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 210, 40));

        BtnVolverAlMenu.setBackground(new java.awt.Color(102, 0, 102));
        BtnVolverAlMenu.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BtnVolverAlMenu.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolverAlMenu.setText("Volver al Inicio");
        BtnVolverAlMenu.setBorder(null);
        BtnVolverAlMenu.setContentAreaFilled(false);
        BtnVolverAlMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnVolverAlMenu.setOpaque(true);
        BtnVolverAlMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverAlMenuActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVolverAlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 210, 40));

        BtnModificar.setBackground(new java.awt.Color(102, 0, 102));
        BtnModificar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BtnModificar.setForeground(new java.awt.Color(255, 255, 255));
        BtnModificar.setText("Modificar");
        BtnModificar.setBorder(null);
        BtnModificar.setContentAreaFilled(false);
        BtnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnModificar.setOpaque(true);
        getContentPane().add(BtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 210, 40));

        lblFondo.setForeground(new java.awt.Color(102, 102, 102));
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/fondoMoradoP.jpg"))); // NOI18N
        lblFondo.setPreferredSize(new java.awt.Dimension(760, 590));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        VentanaAgregarPlan form = new VentanaAgregarPlan(procable);
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void BtnVolverAlMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverAlMenuActionPerformed
        MenuPrincipal menu = new MenuPrincipal(procable);
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnVolverAlMenuActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        if((this.procable).planes == null){
            JOptionPane.showMessageDialog(null, "No hay planes por eliminar!");
        }
        else{
            VentanaBuscarPlanPorEliminar formnom = new VentanaBuscarPlanPorEliminar(procable);
            formnom.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnVerMas;
    private javax.swing.JButton BtnVolverAlMenu;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblWorld1;
    // End of variables declaration//GEN-END:variables
}
