/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clasesproyecto.listas.ProCable;
import javax.swing.ImageIcon;

/**
 *
 * @author XavierKrostya
 */
public class VentanaMostrarPersonal extends javax.swing.JFrame {
    
    private ProCable procable;
    private String rut;
    /**
     * Creates new form VentanaMostrarPersonal
     */
    public VentanaMostrarPersonal(ProCable procable, String rut) {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        this.procable = procable;
        this.rut = rut;
        /*Para poder cargar la imagen del icono*/
        setIconImage(new ImageIcon(getClass().getResource("/Imágenes/network.png")).getImage());
        insertarDatos();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWorld1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblRut = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        BtnVolver = new javax.swing.JButton();
        lblNombreEmp = new javax.swing.JLabel();
        lblApellidoEmp = new javax.swing.JLabel();
        lblRutEmp = new javax.swing.JLabel();
        lblMailEmp = new javax.swing.JLabel();
        lblContrasenaEmp = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(370, 540));
        setMinimumSize(new java.awt.Dimension(370, 540));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(354, 540));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWorld1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/user.png"))); // NOI18N
        getContentPane().add(lblWorld1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 140, 160));

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Datos del empleado");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 180, -1));

        lblNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        lblApellido.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(255, 255, 255));
        lblApellido.setText("Apellido:");
        getContentPane().add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        lblRut.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblRut.setForeground(new java.awt.Color(255, 255, 255));
        lblRut.setText("Rut:");
        getContentPane().add(lblRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        lblMail.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblMail.setForeground(new java.awt.Color(255, 255, 255));
        lblMail.setText("Mail:");
        getContentPane().add(lblMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        lblContrasena.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasena.setText("Contraseña:");
        getContentPane().add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        BtnVolver.setBackground(new java.awt.Color(102, 0, 102));
        BtnVolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnVolver.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 120, -1));

        lblNombreEmp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblNombreEmp.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreEmp.setText("Javier Ignacio");
        getContentPane().add(lblNombreEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        lblApellidoEmp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblApellidoEmp.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidoEmp.setText("Ortiz Diaz");
        getContentPane().add(lblApellidoEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        lblRutEmp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblRutEmp.setForeground(new java.awt.Color(255, 255, 255));
        lblRutEmp.setText("20.181.368-9");
        getContentPane().add(lblRutEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        lblMailEmp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblMailEmp.setForeground(new java.awt.Color(255, 255, 255));
        lblMailEmp.setText("jav_ignacio@live.cl");
        getContentPane().add(lblMailEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        lblContrasenaEmp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblContrasenaEmp.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasenaEmp.setText("javier321123");
        getContentPane().add(lblContrasenaEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));

        lblFondo.setForeground(new java.awt.Color(102, 102, 102));
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/fondoMoradoP.jpg"))); // NOI18N
        lblFondo.setMaximumSize(new java.awt.Dimension(370, 540));
        lblFondo.setMinimumSize(new java.awt.Dimension(370, 540));
        lblFondo.setPreferredSize(new java.awt.Dimension(354, 540));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        OpcionPersonal submenu = new OpcionPersonal(procable);
        submenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed

    public void insertarDatos(){
        lblNombreEmp.setText((this.procable).personal.obtenerNombre(rut));
        lblApellidoEmp.setText((this.procable).personal.obtenerApellido(rut));
        lblRutEmp.setText(rut);
        lblMailEmp.setText((this.procable).personal.obtenerMail(rut));
        lblContrasenaEmp.setText((this.procable).personal.obtenerPassword(rut));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVolver;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblApellidoEmp;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblContrasenaEmp;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblMailEmp;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreEmp;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblRutEmp;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblWorld1;
    // End of variables declaration//GEN-END:variables
}
