/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clasesproyecto.listas.ProCable;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author XavierKrostya
 */
public class VentanaEliminarPlan extends javax.swing.JFrame {
    
    private ProCable procable;
    private String nombrePlan;
    /**
     * Creates new form VentanaEliminarPlan
     */
    public VentanaEliminarPlan(ProCable procable, String nombrePlan) {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        this.procable = procable;
        this.nombrePlan = nombrePlan;
        /*Para poder cargar la imagen del icono*/
        setIconImage(new ImageIcon(getClass().getResource("/Imágenes/network.png")).getImage());
        insertarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCantCanalesI = new javax.swing.JLabel();
        lblWorld1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        BtnEliminar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        lblCantCanales = new javax.swing.JLabel();
        lblNombreI = new javax.swing.JLabel();
        lblValorI = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCantCanalesI.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblCantCanalesI.setForeground(new java.awt.Color(255, 255, 255));
        lblCantCanalesI.setText("inserte cant");
        getContentPane().add(lblCantCanalesI, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        lblWorld1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/network_connection_control_panel.png"))); // NOI18N
        getContentPane().add(lblWorld1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 130, 130));

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("¿Seguro que lo desea eliminar?");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 280, -1));

        lblNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        lblValor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblValor.setForeground(new java.awt.Color(255, 255, 255));
        lblValor.setText("Precio:");
        getContentPane().add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        BtnEliminar.setBackground(new java.awt.Color(102, 0, 102));
        BtnEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 120, -1));

        BtnCancelar.setBackground(new java.awt.Color(102, 0, 102));
        BtnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 120, -1));

        lblCantCanales.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblCantCanales.setForeground(new java.awt.Color(255, 255, 255));
        lblCantCanales.setText("Cantidad de Canales:");
        getContentPane().add(lblCantCanales, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        lblNombreI.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblNombreI.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreI.setText("inserte nombre");
        getContentPane().add(lblNombreI, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        lblValorI.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblValorI.setForeground(new java.awt.Color(255, 255, 255));
        lblValorI.setText("inserte precio");
        getContentPane().add(lblValorI, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        lblFondo.setForeground(new java.awt.Color(102, 102, 102));
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/fondoMoradoP.jpg"))); // NOI18N
        lblFondo.setPreferredSize(new java.awt.Dimension(370, 540));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        JOptionPane.showMessageDialog(null, "No se eliminó el plan!");
        OpcionPlan submenu = new OpcionPlan(procable);
        submenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        if((this.procable).eliminarPlan(nombrePlan)){
            JOptionPane.showMessageDialog(null, "El plan fue eliminado con exito!");
            OpcionPlan submenu = new OpcionPlan(procable);
            submenu.setVisible(true);
            dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Ocurrió un error al eliminar el plan!");
        }
    }//GEN-LAST:event_BtnEliminarActionPerformed
    
    public void insertarDatos(){
        String valor = Float.toString((this.procable).planes.obtenerValor(nombrePlan));
        String cantidad = Integer.toString((this.procable).planes.obtenerCantidadCanales(nombrePlan));
        
        lblNombreI.setText(this.nombrePlan);
        lblValorI.setText(valor);
        lblCantCanalesI.setText(cantidad);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JLabel lblCantCanales;
    private javax.swing.JLabel lblCantCanalesI;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreI;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValorI;
    private javax.swing.JLabel lblWorld1;
    // End of variables declaration//GEN-END:variables
}
