/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clasesproyecto.listas.ProCable;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author XavierKrostya
 */
public class VentanaModificarPlan extends javax.swing.JFrame {
    
    private ProCable procable;
    private String nombre;
    /**
     * Creates new form VentanaModificarPlan
     */
    public VentanaModificarPlan(ProCable procable, String nombre) {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        this.procable = procable;
        this.nombre = nombre;
        /*Para poder cargar la imagen del icono*/
        setIconImage(new ImageIcon(getClass().getResource("/Imágenes/network.png")).getImage());
        insertarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSeparador = new javax.swing.JLabel();
        lblTítulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        jTextValor = new javax.swing.JTextField();
        lblCantCanal = new javax.swing.JLabel();
        jTextCanales = new javax.swing.JTextField();
        jbSalir = new javax.swing.JButton();
        jbAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(414, 340));
        jPanel1.setPreferredSize(new java.awt.Dimension(420, 340));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSeparador.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSeparador.setText("________________________________________________");
        jPanel1.add(lblSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        lblTítulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTítulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTítulo.setText("Formulario Plan");
        jPanel1.add(lblTítulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre del Plan:");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jTextNombre.setBackground(new java.awt.Color(51, 51, 51));
        jTextNombre.setForeground(new java.awt.Color(255, 255, 255));
        jTextNombre.setSelectionColor(new java.awt.Color(102, 0, 102));
        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });
        jPanel1.add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 160, 30));

        lblValor.setForeground(new java.awt.Color(255, 255, 255));
        lblValor.setText("Valor del Plan:");
        jPanel1.add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jTextValor.setBackground(new java.awt.Color(51, 51, 51));
        jTextValor.setForeground(new java.awt.Color(255, 255, 255));
        jTextValor.setSelectionColor(new java.awt.Color(102, 0, 102));
        jTextValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 100, 30));

        lblCantCanal.setForeground(new java.awt.Color(255, 255, 255));
        lblCantCanal.setText("Cantidad de Canal:");
        jPanel1.add(lblCantCanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jTextCanales.setBackground(new java.awt.Color(51, 51, 51));
        jTextCanales.setForeground(new java.awt.Color(255, 255, 255));
        jTextCanales.setSelectionColor(new java.awt.Color(102, 0, 102));
        jPanel1.add(jTextCanales, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 100, 30));

        jbSalir.setBackground(new java.awt.Color(102, 0, 102));
        jbSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbSalir.setForeground(new java.awt.Color(255, 255, 255));
        jbSalir.setText("Cancelar");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 130, 30));

        jbAceptar.setBackground(new java.awt.Color(102, 0, 102));
        jbAceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbAceptar.setForeground(new java.awt.Color(255, 255, 255));
        jbAceptar.setText("Aceptar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(jbAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void jTextValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextValorActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        JOptionPane.showMessageDialog(null, "No se modificó el plan!");
        OpcionPlan submenu = new OpcionPlan(procable);
        submenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed

        if(jTextNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Es obligatorio completar el formulario!");
        }
        else{
            if(jTextValor.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Es obligatorio completar el formulario!");
            }
            else{
                if(jTextCanales.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Es obligatorio completar el formulario!");
                }
                else{
                    int valor = Integer.parseInt(jTextValor.getText());
                    int cantidadCanal = Integer.parseInt(jTextCanales.getText());
                    (this.procable).modificarPlan(nombre, jTextNombre.getText(), valor, cantidadCanal);
                    JOptionPane.showMessageDialog(null, "Plan modificado con exito!");
                    (this.procable).mostrarPlanes();
                    OpcionPlan submenu = new OpcionPlan(procable);
                    submenu.setVisible(true);
                    dispose();
                }
            }
        }
    }//GEN-LAST:event_jbAceptarActionPerformed
    
    private void insertarDatos(){
        jTextNombre.setText((this.procable).obtenerNombrePlan(nombre));
        jTextValor.setText(Float.toString((this.procable).obtenerValorPlan(nombre)));
        jTextCanales.setText(Integer.toString((this.procable).obtenerCantidadCanalesPlan(nombre)));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextCanales;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextValor;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel lblCantCanal;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSeparador;
    private javax.swing.JLabel lblTítulo;
    private javax.swing.JLabel lblValor;
    // End of variables declaration//GEN-END:variables
}
