/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clasesproyecto.listas.ProCable;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author XavierKrostya
 */
public class VentanaPersonalModificar extends javax.swing.JFrame {
    
    private ProCable procable;
    private String rut;
    /**
     * Creates new form VentanaPersonalModificar
     */
    public VentanaPersonalModificar(ProCable procable, String rut) {
        initComponents();
         this.setLocationRelativeTo(null);
        setResizable(false);
        this.procable = procable;
        this.rut = rut;
        /*Para poder cargar la imagen del icono*/
        setIconImage(new ImageIcon(getClass().getResource("/Imágenes/network.png")).getImage());
        insertarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSeparador = new javax.swing.JLabel();
        lblNombre2 = new javax.swing.JLabel();
        lblApellido2 = new javax.swing.JLabel();
        lblRut2 = new javax.swing.JLabel();
        lblpassword2 = new javax.swing.JLabel();
        jTextNombre2 = new javax.swing.JTextField();
        jTextApellido2 = new javax.swing.JTextField();
        jTextPassword2 = new javax.swing.JTextField();
        jTextMail = new javax.swing.JTextField();
        jbAceptar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jTextRut = new javax.swing.JTextField();
        lblMail1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Formulario Empleado");
        jPanel3.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 46));

        lblSeparador.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSeparador.setText("___________________________________________________");
        jPanel3.add(lblSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        lblNombre2.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre2.setText("Nombre:");
        jPanel3.add(lblNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 60, 30));

        lblApellido2.setForeground(new java.awt.Color(255, 255, 255));
        lblApellido2.setText("Apellido:");
        jPanel3.add(lblApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 60, 30));

        lblRut2.setForeground(new java.awt.Color(255, 255, 255));
        lblRut2.setText("Rut:   ");
        jPanel3.add(lblRut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 40, 30));

        lblpassword2.setForeground(new java.awt.Color(255, 255, 255));
        lblpassword2.setText("Contraseña:");
        jPanel3.add(lblpassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 70, 30));

        jTextNombre2.setBackground(new java.awt.Color(51, 51, 51));
        jTextNombre2.setForeground(new java.awt.Color(255, 255, 255));
        jTextNombre2.setSelectionColor(new java.awt.Color(102, 0, 102));
        jPanel3.add(jTextNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 140, -1));

        jTextApellido2.setBackground(new java.awt.Color(51, 51, 51));
        jTextApellido2.setForeground(new java.awt.Color(255, 255, 255));
        jTextApellido2.setSelectionColor(new java.awt.Color(102, 0, 102));
        jPanel3.add(jTextApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 140, -1));

        jTextPassword2.setBackground(new java.awt.Color(51, 51, 51));
        jTextPassword2.setForeground(new java.awt.Color(255, 255, 255));
        jTextPassword2.setSelectionColor(new java.awt.Color(102, 0, 102));
        jTextPassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPassword2ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 160, -1));

        jTextMail.setBackground(new java.awt.Color(51, 51, 51));
        jTextMail.setForeground(new java.awt.Color(255, 255, 255));
        jTextMail.setSelectionColor(new java.awt.Color(102, 0, 102));
        jTextMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMailActionPerformed(evt);
            }
        });
        jPanel3.add(jTextMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 160, -1));

        jbAceptar.setBackground(new java.awt.Color(102, 0, 102));
        jbAceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbAceptar.setForeground(new java.awt.Color(255, 255, 255));
        jbAceptar.setText("Aceptar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });
        jPanel3.add(jbAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 130, 30));

        jbSalir.setBackground(new java.awt.Color(102, 0, 102));
        jbSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbSalir.setForeground(new java.awt.Color(255, 255, 255));
        jbSalir.setText("Cancelar");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jPanel3.add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 130, 30));

        jTextRut.setBackground(new java.awt.Color(51, 51, 51));
        jTextRut.setForeground(new java.awt.Color(255, 255, 255));
        jTextRut.setSelectionColor(new java.awt.Color(102, 0, 102));
        jTextRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRutActionPerformed(evt);
            }
        });
        jPanel3.add(jTextRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 140, -1));

        lblMail1.setForeground(new java.awt.Color(255, 255, 255));
        lblMail1.setText("Mail:");
        jPanel3.add(lblMail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPassword2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPassword2ActionPerformed

    private void jTextMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMailActionPerformed

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed

        if(jTextNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Es obligatorio completar el formulario!");
        }
        else{
            if(jTextApellido.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Es obligatorio completar el formulario!");
            }
            else{
                if(jTextRut.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Es obligatorio completar el formulario!");
                }
                else{
                    if(jTextMail.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "Es obligatorio completar el formulario!");
                    }
                    else{
                        if(jTextPassword.getText().equals("")){
                            JOptionPane.showMessageDialog(null, "Es obligatorio completar el formulario!");
                        }
                        else{
                            (this.procable).modificarPersonal(jTextNombre2.getText(), jTextApellido2.getText(), jTextRut.getText(),rut, jTextMail.getText(), jTextPassword2.getText());
                            JOptionPane.showMessageDialog(null, "Empleado modificado con exito!");
                            OpcionPersonal submenu = new OpcionPersonal(procable);
                            submenu.setVisible(true);
                            dispose();
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_jbAceptarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        OpcionClientes submenu = new OpcionClientes(procable);
        submenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jTextRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRutActionPerformed
    
    public void insertarDatos(){
        jTextNombre2.setText((this.procable).personal.obtenerNombre(rut));
        jTextApellido2.setText((this.procable).personal.obtenerApellido(rut));
        jTextRut.setText(rut);
        jTextMail.setText((this.procable).personal.obtenerMail(rut));
        jTextPassword2.setText((this.procable).personal.obtenerPassword(rut));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JTextField jTextApellido1;
    private javax.swing.JTextField jTextApellido2;
    private javax.swing.JTextField jTextMail;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextNombre1;
    private javax.swing.JTextField jTextNombre2;
    private javax.swing.JTextField jTextPassword;
    private javax.swing.JTextField jTextPassword1;
    private javax.swing.JTextField jTextPassword2;
    private javax.swing.JTextField jTextRut;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblApellido2;
    private javax.swing.JLabel lblMail1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblRut1;
    private javax.swing.JLabel lblRut2;
    private javax.swing.JLabel lblSeparador;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblpassword1;
    private javax.swing.JLabel lblpassword2;
    // End of variables declaration//GEN-END:variables
}
